"""
q=targetingCriteria&cmTargetingCriteria=(include:(and:List(
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aindustries,name:Company%20Industries),segments:List((urn:urn%3Ali%3Aindustry%3A114,name:Nanotechnology,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A118,name:Computer%20%26%20Network%20Security,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A119,name:Wireless,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A24,name:Consumer%20Electronics,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A3,name:Computer%20Hardware,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A4,name:Computer%20Software,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A5,name:Computer%20Networking,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A6,name:Internet,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A7,name:Semiconductors,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A8,name:Telecommunications,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A96,name:Information%20Technology%20%26%20Services,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AprofileLocations,name:Profile%20Locations),segments:List((urn:urn%3Ali%3Ageo%3A103644278,name:United%20States,facetUrn:urn%3Ali%3AadTargetingFacet%3AprofileLocations))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales,name:Interface%20Locales),segments:List((urn:urn%3Ali%3Alocale%3Aen_US,name:English,facetUrn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AmemberBehaviors,name:Member%20Traits),segments:List((urn:urn%3Ali%3AmemberBehavior%3A18,name:Recently%20Promoted,facetUrn:urn%3Ali%3AadTargetingFacet%3AmemberBehaviors))))))),
    exclude:(or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aemployers,name:Company%20Names),segments:List((urn:urn%3Ali%3Acompany%3A1035,name:Microsoft,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A10667,name:Facebook,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A1441,name:Google,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A162479,name:Apple,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A2382910,name:Amazon%20Web%20Services%20%28AWS%29,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers))))))&withValidation=true
"""


"""
q=targetingCriteria&cmTargetingCriteria=(include:(and:List(
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales,name:Interface%20Locales),segments:List((urn:urn%3Ali%3Alocale%3Aen_US,name:English,facetUrn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Alocations,name:Locations),segments:List((urn:urn%3Ali%3Ageo%3A103644278,name:United%20States,facetUrn:urn%3Ali%3AadTargetingFacet%3AprofileLocations))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aindustries,name:Company%20Industries),segments:List((urn:urn%3Ali%3Aindustry%3A6,name:Internet,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A96,name:Information%20Technology%20%26%20Services,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A4,name:Computer%20Software,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A118,name:Computer%20%26%20Network%20Security,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A3,name:Computer%20Hardware,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A5,name:Computer%20Networking,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A119,name:Wireless,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A8,name:Telecommunications,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A7,name:Semiconductors,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A114,name:Nanotechnology,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),(urn:urn%3Ali%3Aindustry%3A24,name:Consumer%20Electronics,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AmemberBehaviors,name:Member%20Traits),segments:List((urn:urn%3Ali%3AmemberBehavior%3A18,name:Recently Promoted,facetUrn:urn%3Ali%3AadTargetingFacet%3AmemberBehaviors))))))),
    exclude:(or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aemployers,name:Company%20Names),segments:List((urn:urn%3Ali%3Acompany%3A10667,name:Facebook,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A162479,name:Apple,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A2382910,name:Amazon%20Web%20Services%20%28AWS%29,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A1035,name:Microsoft,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers),(urn:urn%3Ali%3Acompany%3A1441,name:Google,facetUrn:urn%3Ali%3AadTargetingFacet%3Aemployers))))))
"""