"""
q=targetingCriteria&cmTargetingCriteria=(include:(and:List(
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales,name:Interface%20Locales),segments:List((urn:urn%3Ali%3Alocale%3Aen_US,name:English,facetUrn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Alocations,name:Locations),segments:List((urn:urn%3Ali%3Ageo%3A103644278,name:United%20States,facetUrn:urn%3Ali%3AadTargetingFacet%3Alocations))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Agenders,name:Member%20Gender),segments:List((urn:urn%3Ali%3Agender%3AFEMALE,name:Female,facetUrn:urn%3Ali%3AadTargetingFacet%3Agenders))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aindustries,name:Company%20Industries),segments:List(
        (urn:urn%3Ali%3Aindustry%3A6,name:Internet,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A96,name:Information%20Technology%20%26%20Services,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A4,name:Computer%20Software,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A118,name:Computer%20%26%20Network%20Security,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A3,name:Computer%20Hardware,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A5,name:Computer%20Networking,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A119,name:Wireless,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A8,name:Telecommunications,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A7,name:Semiconductors,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A114,name:Nanotechnology,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A24,name:Consumer%20Electronics,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AageRanges,name:Member%20Age),segments:List((urn:urn%3Ali%3AageRange%3A%2818%2C24%29,name:18%20to%2024,facetUrn:urn%3Ali%3AadTargetingFacet%3AageRanges))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aseniorities,name:Job%20Seniorities),segments:List((urn:urn%3Ali%3Aseniority%3A1,name:Unpaid,facetUrn:urn%3Ali%3AadTargetingFacet%3Aseniorities))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AstaffCountRanges,name:Company%20Size),segments:List((urn:urn%3Ali%3AstaffCountRange%3A%28501%2C1000%29,name:501-1000%20employees,facetUrn:urn%3Ali%3AadTargetingFacet%3AstaffCountRanges))))))),
    exclude:(or:List()))
"""

"""
q=targetingCriteria&cmTargetingCriteria=(include:(and:List(
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales,name:Interface%20Locales),segments:List((urn:urn%3Ali%3Alocale%3Aen_US,name:English,facetUrn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Agenders,name:Member%20Gender),segments:List((urn:urn%3Ali%3Agender%3AFEMALE,name:Female,facetUrn:urn%3Ali%3AadTargetingFacet%3Agenders))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Alocations,name:Locations),segments:List((urn:urn%3Ali%3Ageo%3A103644278,name:United%20States,facetUrn:urn%3Ali%3AadTargetingFacet%3Alocations,ancestorUrns:List(urn%3Ali%3Ageo%3A102221843)))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aindustries,name:Company%20Industries),segments:List(
        (urn:urn%3Ali%3Aindustry%3A118,name:Computer%20%26%20Network%20Security,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A4,name:Computer%20Software,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A96,name:Information%20Technology%20%26%20Services,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A6,name:Internet,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A3,name:Computer%20Hardware,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A5,name:Computer%20Networking,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A114,name:Nanotechnology,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A7,name:Semiconductors,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A8,name:Telecommunications,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A119,name:Wireless,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A24,name:Consumer%20Electronics,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AageRanges,name:Member%20Age),segments:List((urn:urn%3Ali%3AageRange%3A%2818%2C24%29,name:18%20to%2024,facetUrn:urn%3Ali%3AadTargetingFacet%3AageRanges))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aseniorities,name:Job%20Seniorities),segments:List((urn:urn%3Ali%3Aseniority%3A1,name:Unpaid,facetUrn:urn%3Ali%3AadTargetingFacet%3Aseniorities))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AstaffCountRanges,name:Company%20Size),segments:List((urn:urn%3Ali%3AstaffCountRange%3A%281%2C1%29,name:Myself%20Only,facetUrn:urn%3Ali%3AadTargetingFacet%3AstaffCountRanges))))))),
exclude:(or:List()))&withValidation=true
"""