"""
q=targetingCriteria&cmTargetingCriteria=(include:(and:List(
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales,name:Interface%20Locales),segments:List((urn:urn%3Ali%3Alocale%3Aen_US,name:English,facetUrn:urn%3Ali%3AadTargetingFacet%3AinterfaceLocales))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aindustries,name:Company%20Industries),segments:List(
        (urn:urn%3Ali%3Aindustry%3A41,name:Banking,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A129,name:Capital%20Markets,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A43,name:Financial%20Services,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A42,name:Insurance,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A45,name:Investment%20Banking,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A46,name:Investment%20Management,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries),
        (urn:urn%3Ali%3Aindustry%3A106,name:Venture%20Capital%20%26%20Private%20Equity,facetUrn:urn%3Ali%3AadTargetingFacet%3Aindustries))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Alocations,name:Locations),segments:List((urn:urn%3Ali%3Ageo%3A103644278,name:United%20States,facetUrn:urn%3Ali%3AadTargetingFacet%3Alocations))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Agenders,name:Member%20Gender),segments:List((urn:urn%3Ali%3Agender%3AMALE,name:Male,facetUrn:urn%3Ali%3AadTargetingFacet%3Agenders))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AageRanges,name:Member%20Age),segments:List((urn:urn%3Ali%3AageRange%3A%2818%2C24%29,name:18%20to%2024,facetUrn:urn%3Ali%3AadTargetingFacet%3AageRanges))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3Aseniorities,name:Job%20Seniorities),segments:List((urn:urn%3Ali%3Aseniority%3A4,name:Senior,facetUrn:urn%3Ali%3AadTargetingFacet%3Aseniorities))))),
    (or:List((facet:(urn:urn%3Ali%3AadTargetingFacet%3AstaffCountRanges,name:Company%20Size),segments:List((urn:urn%3Ali%3AstaffCountRange%3A%28501%2C1000%29,name:501-1000%20employees,facetUrn:urn%3Ali%3AadTargetingFacet%3AstaffCountRanges))))))),
    exclude:(or:List()))
"""